import { Link } from "react-router-dom";
import "./Home.css";

export default function Home() {
  return (
    <div className="home">

      {/* NAVBAR */}
      <nav className="nav">
        <div className="logo">
          <img src="/images/logo.png" alt="CURA AI"/>
          <span>CURA AI</span>
        </div>

        <div className="navLinks">
          <Link to="/home">Home</Link>
          <Link to="/symptoms">Symptom Checker</Link>
          <Link to="/chat">AI Doctor</Link>
        </div>
      </nav>

      {/* HERO */}
      <section className="hero">
        <div className="heroText">
          <h1>
            AI-powered healthcare<br/>
            for <span>everyone</span>
          </h1>

          <p>
            CURA AI uses machine learning and medical AI to help you detect diseases,
            consult an AI doctor and generate professional medical reports.
          </p>

          <div className="heroBtns">
            <Link to="/symptoms" className="primaryBtn">
              Check Your Symptoms
            </Link>
            <Link to="/chat" className="secondaryBtn">
              Talk to AI Doctor
            </Link>
          </div>
        </div>

        <div className="heroImg">
          <img src="/images/hero-heart.png" alt="AI Doctor"/>
        </div>
      </section>

      {/* FEATURES */}
      <section className="features">
        <div className="featureCard">
          <img src="/icons/protection.png"/>
          <h3>Disease Prediction</h3>
          <p>
            Our AI analyzes your symptoms and predicts possible diseases
            with high accuracy.
          </p>
        </div>

        <div className="featureCard">
          <img src="/icons/stethoscope.png"/>
          <h3>AI Doctor</h3>
          <p>
            Get medical guidance, precautions and home care advice
            from our intelligent AI doctor.
          </p>
        </div>

        <div className="featureCard">
          <img src="/icons/report.png"/>
          <h3>Medical Reports</h3>
          <p>
            Download hospital-style medical reports generated by CURA AI.
          </p>
        </div>

        <div className="featureCard">
          <img src="/icons/security.png"/>
          <h3>Secure & Private</h3>
          <p>
            Your health information is encrypted and never shared.
          </p>
        </div>
      </section>
{/* ABOUT CURA AI */}
<section className="about">
  <div className="aboutLeft">
    <p className="aboutSmall">( SINCE 2025 )</p>
    <h4>About CURA AI</h4>

    <img 
      src="/images/medical.png" 
      alt="CURA AI"
      className="aboutImg"
    />
  </div>

  <div className="aboutRight">
    <p className="aboutBigText">
      At CURA AI, we make healthcare smart, fast, and accessible for everyone.
      Our mission is to use artificial intelligence to help people detect diseases early,
      consult an AI doctor anytime, and generate hospital-style medical reports,
      ensuring you receive the right care without delays or confusion.
    </p>
  </div>
</section>
{/* CURA AI SERVICES */}
<section className="curaServices">
  <h2>
    Our AI healthcare <span>services</span>
  </h2>
  <p className="subText">
    CURA AI combines machine learning and medical intelligence to give you
    fast, reliable, and private healthcare anytime.
  </p>

  <div className="servicesGrid">

    <div className="serviceCard">
      <span>01</span>
      <h3>AI Disease Prediction</h3>
      <p>
        Analyze your symptoms using machine learning to detect possible
        diseases early.
      </p>
    </div>

    <div className="serviceCard">
      <span>02</span>
      <h3>AI Doctor Consultation</h3>
      <p>
        Chat with an intelligent AI doctor for medical advice,
        precautions and home care guidance.
      </p>
    </div>

    <div className="serviceCard">
      <span>03</span>
      <h3>Symptom Checker</h3>
      <p>
        Select your symptoms and get instant health insights
        without visiting a clinic.
      </p>
    </div>

    <div className="serviceCard">
      <span>04</span>
      <h3>Medical Report Generator</h3>
      <p>
        Download professional hospital-style medical reports
        generated by CURA AI.
      </p>
    </div>

    <div className="serviceCard">
      <span>05</span>
      <h3>Doctor Recommendation</h3>
      <p>
        Get the right doctor suggestion like cardiologist,
        pulmonologist, or general physician.
      </p>
    </div>

    <div className="serviceCard">
      <span>06</span>
      <h3>Secure Health Records</h3>
      <p>
        Your health data is encrypted, private and never shared
        with anyone.
      </p>
    </div>

  </div>
</section>

      {/* HOW IT WORKS */}
      <section className="how">
        <h2>How CURA AI Works</h2>
        <div className="steps">
          <div>1️⃣ Enter your symptoms</div>
          <div>2️⃣ Get AI disease prediction</div>
          <div>3️⃣ Talk with AI doctor</div>
          <div>4️⃣ Download your medical report</div>
        </div>
      </section>

      {/* CTA */}
      <section className="cta">
        <h2>Smarter healthcare starts here.</h2>
        <Link to="/symptoms" className="primaryBtn">
          Start Health Check
        </Link>
      </section>

      {/* FOOTER */}
      <footer>
        <p>© 2026 CURA AI — Intelligent Medical Assistant</p>
      </footer>

    </div>
  );
}
