import { Link } from "react-router-dom";
import "./Home.css";
import { useState } from "react";
/* ---------------- FAQ DATA ---------------- */
const faqData = [
  {
    q: "How do I check my disease on CURA AI?",
    a: "Go to the Symptom Checker, select your symptoms and CURA AI will instantly predict possible diseases."
  },
  {
    q: "Is the AI doctor real?",
    a: "CURA AI uses advanced medical AI trained on healthcare data to give safe and helpful medical guidance."
  },
  {
    q: "Can I download my medical report?",
    a: "Yes. After disease prediction you can download a professional hospital-style medical report."
  },
  {
    q: "Is my health data safe?",
    a: "Yes. Your health data is encrypted and never shared with anyone."
  },
  {
    q: "What problems can I consult for?",
    a: "You can check fever, infections, breathing issues, stomach problems, diabetes, blood pressure and many more."
  }
];

/* ---------------- FAQ COMPONENT ---------------- */
function FAQAccordion() {
  const [active, setActive] = useState(0);

  return (
    <div className="faqRight">
      {faqData.map((item, i) => (
        <div
          key={i}
          className={`faqItem ${active === i ? "active" : ""}`}
          onClick={() => setActive(active === i ? null : i)}
        >
          <div className="faqQuestion">
            <span>{item.q}</span>
            <img
              src={active === i ? "/images/drop-down.png" : "/images/drop.png"}
              className="faqArrow"
            />
          </div>

          {active === i && <p className="faqAnswer">{item.a}</p>}
        </div>
      ))}
    </div>
  );
}
export default function Home() {
  return (
    <div className="home">

      {/* NAVBAR */}
      <nav className="nav">
        <div className="logo">
          <img src="/images/ai-robot.png" alt="CURA AI"/>
          <span>CURA AI</span>
        </div>

        <div className="navLinks">
          <Link to="/home">Home</Link>
          <Link to="/symptoms">Symptom Checker</Link>
          <Link to="/chat">AI Doctor</Link>
        </div>
      </nav>

      {/* HERO */}
      <section className="hero">
        <div className="heroText">
          <h1>
            AI-powered healthcare<br/>
            for <span>everyone</span>
          </h1>

          <p>
            CURA AI uses machine learning and medical AI to help you detect diseases,
            consult an AI doctor and generate professional medical reports.
          </p>

          <div className="heroBtns">
            <Link to="/symptoms" className="primaryBtn">
              Check Your Symptoms
            </Link>
            <Link to="/chat" className="secondaryBtn">
              Talk to AI Doctor
            </Link>
          </div>
        </div>

        <div className="heroImg">
          <img src="/images/ai-robot.png" alt="AI Doctor"/>
        </div>
      </section>

      {/* FEATURES */}
      <section className="features">
        <div className="featureCard">
          <img src="/icons/protection.png"/>
          <h3>Disease Prediction</h3>
          <p>
            Our AI analyzes your symptoms and predicts possible diseases
            with high accuracy.
          </p>
        </div>

        <div className="featureCard">
          <img src="/icons/stethoscope.png"/>
          <h3>AI Doctor</h3>
          <p>
            Get medical guidance, precautions and home care advice
            from our intelligent AI doctor.
          </p>
        </div>

        <div className="featureCard">
          <img src="/icons/report.png"/>
          <h3>Medical Reports</h3>
          <p>
            Download hospital-style medical reports generated by CURA AI.
          </p>
        </div>

        <div className="featureCard">
          <img src="/icons/security.png"/>
          <h3>Secure & Private</h3>
          <p>
            Your health information is encrypted and never shared.
          </p>
        </div>
      </section>
{/* ABOUT CURA AI */}
<section className="about">
  <div className="aboutLeft">
    
    <h4>About CURA AI</h4>

    <img 
      src="/images/medical.png" 
      alt="CURA AI"
      className="aboutImg"
    />
  </div>

  <div className="aboutRight">
    <p className="aboutBigText">
      At CURA AI, we make healthcare smart, fast, and accessible for everyone.
      Our mission is to use artificial intelligence to help people detect diseases early,
      consult an AI doctor anytime, and generate hospital-style medical reports,
      ensuring you receive the right care without delays or confusion.
    </p>
  </div>
</section>
{/* CURA AI SERVICES */}
<section className="curaServices">
  <h2>
    Our AI healthcare <span>services</span>
  </h2>
  <p className="subText">
    CURA AI combines machine learning and medical intelligence to give you
    fast, reliable, and private healthcare anytime.
  </p>

  <div className="servicesGrid">

    <div className="serviceCard">
      <span>01</span>
      <h3>AI Disease Prediction</h3>
      <p>
        Analyze your symptoms using machine learning to detect possible
        diseases early.
      </p>
    </div>

    <div className="serviceCard">
      <span>02</span>
      <h3>AI Doctor Consultation</h3>
      <p>
        Chat with an intelligent AI doctor for medical advice,
        precautions and home care guidance.
      </p>
    </div>

    <div className="serviceCard">
      <span>03</span>
      <h3>Symptom Checker</h3>
      <p>
        Select your symptoms and get instant health insights
        without visiting a clinic.
      </p>
    </div>

    <div className="serviceCard">
      <span>04</span>
      <h3>Medical Report Generator</h3>
      <p>
        Download professional hospital-style medical reports
        generated by CURA AI.
      </p>
    </div>

    <div className="serviceCard">
      <span>05</span>
      <h3>Doctor Recommendation</h3>
      <p>
        Get the right doctor suggestion like cardiologist,
        pulmonologist, or general physician.
      </p>
    </div>

    <div className="serviceCard">
      <span>06</span>
      <h3>Secure Health Records</h3>
      <p>
        Your health data is encrypted, private and never shared
        with anyone.
      </p>
    </div>

  </div>
</section>
{/* HOW CURA AI WORKS */}
<section className="howWorks">

  <h2>
    How CURA AI <span>works</span>
  </h2>
  <p className="howSub">
    From symptoms to solutions in just four simple steps.
  </p>

  <div className="howLayout">

    {/* LEFT */}
    <div className="howColumn">
      <div className="howCard">
        <span className="stepTag">Step 01</span>
        <h3>Share your symptoms</h3>
        <p>
          Tell CURA AI how you are feeling in simple words or by selecting
          symptoms.
        </p>
      </div>

      <div className="howCard">
        <span className="stepTag">Step 02</span>
        <h3>Get AI diagnosis</h3>
        <p>
          Our machine learning model analyzes your symptoms and predicts
          possible diseases.
        </p>
      </div>
    </div>

    {/* CENTER IMAGE */}
    <div className="howImage">
      <img src="/images/heart.png" alt="Health AI" />
    </div>

    {/* RIGHT */}
    <div className="howColumn">
      <div className="howCard">
        <span className="stepTag">Step 03</span>
        <h3>Talk to AI Doctor</h3>
        <p>
          Chat with our intelligent medical assistant to get treatment
          guidance and precautions.
        </p>
      </div>

      <div className="howCard">
        <span className="stepTag">Step 04</span>
        <h3>Download your report</h3>
        <p>
          Receive a professional medical report with disease details,
          doctor recommendation and advice.
        </p>
      </div>
    </div>

  </div>
</section>

      {/* FAQ */}
      <section className="faqSection">
        <div className="faqLeft">
          <h2>Frequently asked <span>questions</span></h2>
          <img src="/images/thermometer.png"  />
        </div>
        <FAQAccordion />
      </section>


      {/* FOOTER */}
      <footer>
        <p>© 2026 CURA AI — Intelligent Medical Assistant</p>
      </footer>

    </div>
  );
}
